### ISSUE TITLE
Adding empty style tags causes a GET request for 'null'.

### ISSUE THREAD

**Issue by ziqbal** [deltakosh/handjs#2]
On latest firefox/safari (mac) I've noticed strange 404 GET requests for a 'null' page whenever there are style tags in the page.

Adding empty style tags to one of the samples:

&lt;style&gt;
&lt;/style&gt;

Shows errors in firefox and safari console. Internet explorer 9 seems fine.

**Comment by ziqbal** [comment]
Using the hand 'base' js file only resolved the issue!

Thanks for the great library.

**Comment by SaschaNaz** [comment]
8499f0f9117f36759dce5f376e5fa3dd53741cad should fix this issue. Thanks!
